FROM php:8.4-apache

WORKDIR /var/www/html

COPY . /var/www/html
COPY docker/apache-render.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod headers rewrite \
    && sed -ri 's!Listen 80!Listen 10000!g' /etc/apache2/ports.conf \
    && mkdir -p /var/www/html/storage \
    && chown -R www-data:www-data /var/www/html/storage

EXPOSE 10000

CMD ["apache2-foreground"]
