services:
  - type: web
    name: anna-kolesova-portal-demo
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: PORT
        value: "10000"
